# Generated by Django 5.1.7 on 2025-04-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Furniture', 'Furniture'), ('Shoes', 'Shoes'), ('Clothes', 'Clothes'), ('Perfumes', 'Perfumes')], max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
