# Generated by Django 5.1.7 on 2025-04-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chathistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chathistory',
            old_name='chatbot_response',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='chathistory',
            name='recommended_products',
        ),
        migrations.RemoveField(
            model_name='chathistory',
            name='user_message',
        ),
        migrations.AddField(
            model_name='chathistory',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], default='user', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chathistory',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
